# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0002_token_max_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[(b'google', b'Google'), (b'facebook', b'Facebook')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[(b'google', b'Google'), (b'facebook', b'Facebook')], max_length=30, verbose_name='provider'),
        ),
    ]
