# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-01-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_auto_20191205_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[(b'linkedin_oauth2', b'LinkedIn'), (b'google', b'Google'), (b'facebook', b'Facebook')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[(b'linkedin_oauth2', b'LinkedIn'), (b'google', b'Google'), (b'facebook', b'Facebook')], max_length=30, verbose_name='provider'),
        ),
    ]
