# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-12 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_socialapp_cert'),
        ('socialaccount', '0004_auto_20200102_0601'),
    ]

    operations = [
    ]
